<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
<script>

// promise 약속의 의미
// 상점으로 예를들면. 상품이 준비되면 고객에게 연락처로 연락을 하는개념.
// 그 동안 다른 작업을 할 수 있기에 분할작업에 용이하다


const pr = new Promise((resolve, reject) => { // resolve, reject는 콜백함수
    setTimeout(() => {
        // resolve 값은 성공 , reject값은 실패
        //resolve("OK");

        reject(new Error("err....."));
    }, 1000);
});

console.log("시작");
pr.then((result) => { // 값이 정상적으로 출력되는경우 
    console.log(result);
})
.catch((err) =>{ // 값이 에러가뜨는 경우
    console.log(err);
})
.finally(() =>{ // 성공 실패와 상관없이 무조건적으로 출력하는 파이널리
    console.log("끝");
})


console.log("===========================")


// const f1 = (callback) =>{
//     setTimeout(function (){
//         console.log("1번 주문 완료")
//         callback();
//     }, 1000)
// };

// const f2 = (callback) =>{
//     setTimeout(function (){
//         console.log("2번 주문 완료")
//         callback();
//     }, 3000)
// };

// const f3 = (callback) =>{
//     setTimeout(function (){
//         console.log("3번 주문 완료")
//         callback();
//     }, 2000)
// };

// 하기와같은 콜백함수를 계속해서 호출하는것을 콜백지옥이라고한다.
// console.log("시작");
// f1(function(){
//     f2(function(){
//         f3(function(){
//             console.log("끝");
//         })
//     })
// });


const f1 = () =>{
    return new Promise((res, rej) =>{
        setTimeout(() => {
            res("1번주문 완료");
        }, 1000);       
    });
};

const f2 = (message) =>{
    console.log(message);
    return new Promise((res, rej) =>{
        setTimeout(() => {
            //res("2번주문 완료");
            rej(new Error("err......"));
        }, 3000);       
    });
};


const f3 = (message) =>{
    console.log(message);
    return new Promise((res, rej) =>{
        setTimeout(() => {
            res("3번주문 완료");
        }, 2000);       
    });
};



// console.log("시작");
// f1()
// .then((res) => f2(res))
// .then((res) => f3(res))
// .then((res) => console.log(res))
// .catch(console.log)
// .finally(()=>{
//     console.log("끝");
// });


// async,await을 통해 상품주문을 출력해보기

console.log("시작")
async function order(){
    // 어씽크 어웨잇은 아래와같이 트라이 캐취문으로 작성한다. 정상작동시 트라이문이 비정상작동시 캐취문이 에러를 잡아낸다
    try{
        const result1 = await f1();
        const result2 = await f2(result1);
        const result3 = await f3(result2);
        console.log(result3);
    }catch(e){
        console.log(e)
    }
    console.log("종료");
}
order();

</script>

</body>
</html>